version: "3.8"
services:
  # streamlit:
  #   build:
  #     context: ./user-interface
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "8501:8501"
  #   volumes:
  #     - ./user-interface:/app
  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
